version: '3'
services:
  api:
    container_name: "printScript-service"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${PORT}:${PORT}
    env_file:
      - .env
    networks:
        - wii-network

networks:
    wii-network:
        external: true