version: '3'
services:
  api:
    container_name: "printScript-service"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PRINTSCRIPT_PORT}:${PRINTSCRIPT_PORT}"
    env_file:
      - .env
