spring:
  application:
    name: printScript-service
  constants:
    asset_url: "${BASE_URL}${ASSET_HOST}:${ASSET_PORT}/${ASSET_URL}"
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: ${AUTH_SERVER_URI}

auth0:
    audience: ${AUTH0_AUDIENCE}

server:
  port: ${PRINTSCRIPT_PORT}

ui:
    url: ${UI_URL}